### ISSUE TITLE
Add option not to parse response as JSON

### ISSUE THREAD

**Issue by matus-tomlein** [rokucommunity/roku-requests#12]
It would be great if parsing responses as JSON could be made optional. I am accessing an API that accepts JSON in request body but responds only with the string "ok". This results in errors such as `ERROR: ParseJSON: Unknown identifier 'ok'`.

Could there be an option for it? Alternatively, the parsing could be dependent on the response content-type.

**Comment by TwitchBronBron** [comment]
@matus-tomlein We'd be happy to accept a pull request for this.

**Comment by iBicha** [comment]
@TwitchBronBron since the package is at 0.2.0, wouldn't it be better to introduce a breaking change, and make `json` into a method `json()`?
